### ISSUE TITLE
Not able to Install 

### ISSUE THREAD

**Issue by ankush0128** [sjessa/cytokit#87]

**Comment by ankush0128** [comment]
It is showing some errors while installing! 
###Error: Failed to install 'cytokit' from GitHub:
  System command error, exit status: 1, stdout + stderr (last 10 lines):
`E>` ** R
E> ** data
E> *** moving datasets to lazyload DB
E> ** byte-compile and prepare package for lazy loading
E> Error: class "seurat" is not exported by 'namespace:Seurat'
E> Execution halted
E> ERROR: lazy loading failed for package ‘cytokit’
E> * removing ‘/private/var/folders/st/7_q6h2897zv73w3x6g85m6y80000gn/T/Rtmp80WHwW/Rinstb3b465c4fe52/cytokit’
E>       -----------------------------------
E> ERROR: package installation failed`

**Comment by sjessa** [comment]
Hello! Thanks for your interest in the package - `cytokit` is no longer being developed, so I invite you to check out the newer package `cytobox` at https://github.com/fungenomics/cytobox/ and I'll close this issue. I have updated the READMEs of both packages so that this is more clear.
